title: "slama.dev"
description: "Tomáš Sláma's personal website."
url: "https://slama.dev"

baseurl: ""

# exclude Jekyll-related files, scripts and generated content
exclude:
  [
    "climbing/*.py",
    "k/*.py",
    "climbing/videos/unblurred/",
    "ignored/",
    "LICENSE",
    "makefile",
    "README.md",
    "requirements.txt",
    "scripts/",
    "*.xopp",
    "*.yaml",
    "*.conf",
    "site",
  ]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:slugified_categories/:title/

jektex:
  silent: true

plugins:
  - jektex

# Halloween theme configuration
halloween:
  enabled: true
